baseURL = 'https://meetups.nabarun.dev'
languageCode = 'en-us'
title = 'Cloud Native Platform Engineering'
theme = 'typo'

[params]
# homeIntroTitle = 'Hi!'
homeIntroContent = """
Platform engineering is an emerging discipline in the cloud-native landscape, focusing on creating
robust internal developer platforms that streamline the development and deployment of applications.
This approach is pivotal as it addresses the complexities inherent in modern software architectures, which
often involve intricate cloud-native technologies such as Kubernetes and microservices. By providing a
standardized and automated platform, platform engineering allows developers to focus on writing code and
delivering business value, rather than being bogged down by infrastructure setup and maintenance.

We are a passionate group of individuals organizing meetups to discuss about new developments in the
intersection of Platform Engineering and Cloud Native projects.

### [The next meetup is on 14th of September 2024. CFP and Registrations are open!](/next)

"""

homeCollectionTitle = 'Past Meetups'
homeCollection = 'meetups'
paginationSize = 100
hidePagination = true

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "next meetup"
url = "/next"

[[params.menu]]
name = "past meetups"
url = "/meetups"

# [[params.menu]]
# name = "about"
# url = "/about"

[[params.menu]]
name = "code of conduct"
url = "/coc"
